### ISSUE TITLE
account_invoice_report_grouped_by_picking

### ISSUE THREAD

**Issue by JHernandezConinpe** [OCA/account-invoice-reporting#277]
## Module
account_invoice_report_grouped_by_picking

## Describe the bug
I have tested in module account_invoice_report_grouped_by_picking the function show section and notes in runboat and it does´nt work

## To Reproduce
**Affected versions**: v13.0

1. Create invoice 
2. Add product, note and sections
3. Print invoice

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Unless you give more details, there's no clear view of which is the problem.

**Comment by JHernandezConinpe** [comment]
Notes and sections lines are not displayed in pdf

**Comment by pedrobaeza** [comment]
Please indicate the exact steps to get to the problem, as on regular use, they are shown.

**Comment by JHernandezConinpe** [comment]
I create two sales orders to which I add notes and sections, deliver the quantities of stockable products, then invoice the two orders and print the invoice and the packing slip grouping works fine, but the notes and sections do not appear.
Then I try to create an invoice and add products, notes and sections and when I print it, they do not appear either.

**Comment by pedrobaeza** [comment]
Please replicate it on a runboat instance and link the documents here.

**Comment by JHernandezConinpe** [comment]
This is my example:
![Selección_219](https://github.com/OCA/account-invoice-reporting/assets/94530807/6da73371-b2f3-42ed-8ccb-39d86bad180c)
![Selección_220](https://github.com/OCA/account-invoice-reporting/assets/94530807/0a40a38e-2f5f-4504-92b9-ab950d275a0b)

**Comment by pedrobaeza** [comment]
Please paste here the link for not having to type it.

**Comment by JHernandezConinpe** [comment]
http://oca-account-invoice-reporting-13-0-5ee32a2ee187.runboat.odoo-community.org/web#id=13&action=318&active_id=4&model=account.move&view_type=form&cids=&menu_id=231

**Comment by pedrobaeza** [comment]
Since #259, it should work. I see your tests are not done on the latest runboat. Can you please try in http://oca-account-invoice-reporting-15-0-c1d56c39e3a5.runboat.odoo-community.org ?

**Comment by JHernandezConinpe** [comment]
The version I am testing is v13 that link is for v15.

**Comment by JHernandezConinpe** [comment]
Since this: https://github.com/OCA/account-invoice-reporting/pull/258

**Comment by pedrobaeza** [comment]
Yeah, the idea is that PR improves this.

@carlosdauden can you check the case for the SO http://oca-account-invoice-reporting-13-0-5ee32a2ee187.runboat.odoo-community.org/web#id=26&action=411&model=sale.order&view_type=form&cids=&menu_id=231 ?

**Comment by linuxivan** [comment]
Still not working.

**Comment by carlosdauden** [comment]
Fixed in https://github.com/OCA/account-invoice-reporting/pull/278
Please review

**Comment by AsierAcedo** [comment]
in #278 still happening the bug check this [http://oca-account-invoice-reporting-13-0-pr278-5d0ea7c979a6.runboat.odoo-community.org/web#id=10&action=318&active_id=2&model=account.move&view_type=form&cids=&menu_id=231](http://oca-account-invoice-reporting-13-0-pr278-5d0ea7c979a6.runboat.odoo-community.org/web#id=10&action=318&active_id=2&model=account.move&view_type=form&cids=&menu_id=231) in this example inside the invoice report the last note of all lines is duplicated at beggining of the invoice lines

**Comment by JHernandezConinpe** [comment]
I tested #278 in http://oca-account-invoice-reporting-13-0-pr278-5d0ea7c979a6.runboat.odoo-community.org/web#id=16&action=318&active_id=8&model=account.move&view_type=form&cids=&menu_id=231.
Some notes and sections do not correspond to the source order:
![imagen](https://github.com/OCA/account-invoice-reporting/assets/94530807/74e95afe-f638-4661-bf03-bdbff87ef67d)
![imagen](https://github.com/OCA/account-invoice-reporting/assets/94530807/0bf285e7-5961-42b4-9a8a-b6b88ae10c84)

**Comment by JHernandezConinpe** [comment]
Then I tried in #278 a simple invoice:
http://oca-account-invoice-reporting-13-0-pr278-5d0ea7c979a6.runboat.odoo-community.org/web#id=17&action=318&active_id=8&model=account.move&view_type=form&cids=1&menu_id=231
![imagen](https://github.com/OCA/account-invoice-reporting/assets/94530807/490d1de2-2b0e-441b-8521-0fac1eae7272)
![imagen](https://github.com/OCA/account-invoice-reporting/assets/94530807/9e18720b-b046-4975-99d4-75a6eb128a67)

**Comment by TelmoSuarezConinpe** [comment]
While applying #259 to v14.0 in #267 I have made some changes that could help.

**Comment by GuillermoBonet** [comment]
Good morning,

we have a client in v16 that has de same last problem: when the invoice has a note line, all picking that are down this note line in the sequence, introduce this comment. I did a pull of the 16.0 branch for take a look if there are a solution, but the error persist. Attach images about the example

![image](https://github.com/user-attachments/assets/b549193f-a94c-4270-82b7-5492d834faf3)

In this case we see a comment in the middle of lines because this comment is in one specific picking.

![image](https://github.com/user-attachments/assets/829fe173-ca57-49f1-b014-cdf9697d5778)

This image show all lines that are after the note.

![image](https://github.com/user-attachments/assets/13595824-c8a6-4fc8-9073-c1ea526feef3)

The last image show all lines that are before the note. As you can see they don't have the comment.

Are someone working in this bug?

Thanks for your time.

best regard
